INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Computer', 'computer product detail', 599.99, 3);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Mask', 'mask product detail', 19.99, 100);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Headphone', 'Headphone product detail', 299.99, 10);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Phone', 'Phone product detail', 699.99, 10);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Shirt', 'Shirt product detail', 10.00, 50);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Frisbee', 'Frisbee product detail', 7.99, 50);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Backpack', 'Backpack product detail', 99.99, 8);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Stickers', 'Stickers product detail', 2.99, 100);
INSERT INTO `bannodidb`.`product` (title, product_detail, price, quantity)
VALUES ('Necklace', 'Necklace product detail', 399.99, 2);